### ISSUE TITLE
Not working on the devices 6.0 and above

### ISSUE THREAD

**Issue by MiTHUN24** [rjeffm/CallRecorder#4]
**The recording function not working in the devices above 6.0 (Marshmallow) and above showing the error**
 

08-10 17:16:18.282 12505-12505/com.jlcsoftware.callrecorder E/MediaRecorder: start failed: -2147483648
08-10 17:16:18.283 12505-12505/com.jlcsoftware.callrecorder W/System.err: java.lang.RuntimeException: start failed.
08-10 17:16:18.283 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.media.MediaRecorder.start(Native Method)
08-10 17:16:18.283 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at com.jlcsoftware.services.RecordCallService.startRecording(RecordCallService.java:103)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at com.jlcsoftware.services.RecordCallService.onStartCommand(RecordCallService.java:45)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3028)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.app.ActivityThread.-wrap17(ActivityThread.java)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1452)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-10 17:16:18.284 12505-12505/com.jlcsoftware.callrecorder W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by rjeffm** [comment]
Likely a permissions problem. You'll have to add permission support.

**Comment by MiTHUN24** [comment]
i have checked it but its not permissions issue 
i have added all the permission but still showing same issue

**Comment by srivishalsangepu** [comment]
Hi rjeffm,
I tried this app in android naughat by giving all the permisssions,the app is installd successfully but the voice is not recorded.

**Comment by MiTHUN24** [comment]
rjeffm can you please solve this bug
